In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_csv('./1429_1.csv')
required_data = data.iloc[:, [11,13,14]]
print(type(required_data))
print(required_data.shape)

<class 'pandas.core.frame.DataFrame'>
(34660, 3)


C:\Users\krish\AppData\Local\Temp\ipykernel_5772\3442358441.py:1: DtypeWarning: Columns (1,10) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('./1429_1.csv')


In [3]:
required_data = required_data.dropna()
print(required_data.shape)

(34064, 3)


In [4]:
do_recommend = np.array(required_data.iloc[:,0])
do_recommend = 1*do_recommend
print(do_recommend)

[1 1 1 ... 1 1 1]


In [5]:
ratings = np.array(required_data.iloc[:,2]).T
print(ratings.shape)

(34064,)


In [6]:
num_helpful = np.array(required_data.iloc[:,1])
print(num_helpful.shape)

(34064,)


In [7]:
x = np.array(np.vstack((ratings, num_helpful)).T)
y = do_recommend
y=y.astype('int')
print(x.shape)
print(y.shape)

(34064, 2)
(34064,)


In [8]:
X_train, X_test, y_train, y_test = train_test_split(x, y)
print('x_train', X_train.shape)
print('x_test', X_test.shape)
print('y_test', y_test.shape)
print('y_train', y_train.shape)

x_train (25548, 2)
x_test (8516, 2)
y_test (8516,)
y_train (25548,)


In [9]:
regressor = LogisticRegression()
regressor.fit(X_train, y_train)

LogisticRegression()

In [10]:
predictions = regressor.predict(X_test)
print(predictions)

[1 1 1 ... 1 1 1]


In [11]:
score = regressor.score(X_test, y_test)
print(score)

0.9744011272898074


In [12]:
cm = confusion_matrix(y_test, predictions)
print(cm)

[[ 154  194]
 [  24 8144]]


In [13]:
from sklearn.metrics import classification_report
 
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.87      0.44      0.59       348
           1       0.98      1.00      0.99      8168

    accuracy                           0.97      8516
   macro avg       0.92      0.72      0.79      8516
weighted avg       0.97      0.97      0.97      8516

